[tool.poetry]
name = "volue.mesh"
version = "0.1.0"
description = ""
license = "Proprietary"
authors = ["Volue AS"]
readme = "README.md"
homepage = "https://github.com/PowelAS/sme-mesh-python"
repository = "https://github.com/PowelAS/sme-mesh-python"
packages = [
    { include = "volue", from = "src" }
]
# By default Poetry doesn't package files in .gitignore.
include = [
    "src/volue/mesh/proto/mesh_pb2.py",
    "src/volue/mesh/proto/mesh_pb2_grpc.py"
]

[tool.poetry.dependencies]
python = "^3.7"
grpcio = "^1.37.0"
pyarrow = "^4.0.1"
protobuf = "^3.17.3"
winkerberos = { version = "^0.8.0", markers = "sys_platform == 'win32'" }
kerberos = { version = "^1.3.1", markers = "sys_platform == 'linux'" }

[tool.poetry.dev-dependencies]
grpcio-tools = "^1.37.0"
Sphinx = "^4.0.2"
sphinx-rtd-theme = "^0.5.2"
rtd = "^1.2.3"
flake8 = "^3.9.2"
pytest = "^6.2.5"
pytest-asyncio = "^0.15.1"

[tool.pytest.ini_options]
markers = [
    "database: Tests that require a running mesh server with a database cache with data. Warning: might read/write to db.",
    "server: Tests that require a running mesh server.",
    "examples: Tests that run the examples.",
    "unittest: Tests that do NOT require a mesh server.",
    "authentication: Tests that require a running mesh server with Kerberos authentication.",
]

[build-system]
requires = [
    "poetry-core>=1.0.3",
    "grpcio-tools>=1.37.0"
]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
script = "build.py"
generate-setup-file = false
