name: Install development environment
description: Workflow installs poetry, Mesh Python SDK and Mesh service

inputs:
  token:
    required: true
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Installing poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: '1.7.1'

    - name: Poetry install
      run: poetry install
      shell: bash

    # Generates the protobuf/gRPC sources and creates the SDK packages
    - name: Poetry build
      run: poetry build
      shell: bash

    - name: Checkout GitHub action
      uses: actions/checkout@v3
      with:
        repository: PowelAS/sme-run-mesh-service
        ref: master
        token: ${{ inputs.token }}
        path: .github/actions

    - name: Install and run Mesh server
      uses: ./.github/actions/
      id: download-mesh-server
      with:
        GITHUB_TOKEN: ${{ inputs.token }}
        MESH_SERVICE_TAG: 'v2.15.0.1975'
