name: Build, test and publish

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  Downloading a mesh server:
    runs-on: windows-latest
    
    steps:
      - name: Download mesh server from github releases
        run: echo "Download mesh server and run."

  Making sure developers can keep developing:
    #TODO: matrix: win, linux, mac (?)
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Sets up the python version we wanna use
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Installs Poetry
      - name: Installing poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.6'

      # Install all the projects development and runtime dependencies to a virtual environment
      - name: Poetry install
        run: poetry install
      
      # Generates the protobuf/grpc sources and creates the api packages
      - name: Poetry build
        run: poetry build
        
      - name: Run Python Unittest with poetry
        run: poetry run python -m unittest discover -s ./tests --pattern=*.py
        
      -name: Upload artiacts
        run: echo "Uploading artifacts needed for the next step"
    
  Users are important:
    #TODO: matrix: win, linux, mac
      runs-on: windows-latest
      
      steps:
        - name: Create virtual environment
          run: echo "Create venv, pip install requirements.txt"
        
        - name: Run script that imports volue.mesh, examples and tests
          run: echo "Using volue.mesh in scripts"
      
        

