# This is a basic workflow to help you get started with Actions

name: Build and test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build_and_test:
  
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    env:
      POETRY_PATH: ${{echo $env:USERPROFILE"/.poetry/bin/poetry.exe"}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Poetry
      - name: Install Poetry
        run: (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -

      # Install all the projects development and runtime dependencies to a virtual environment
      - name: Poetry install
        run: env[POETRY_PATH] install
      
      # Generates the protobuf/grpc sources and creates the api packages
      - name: Poetry build
        run: env[POETRY_PATH] build
        
      - name: Run Python Unittest
        run: env[POETRY_PATH] run python -m unittest tests/all_tests.py
