# This is a basic workflow to help you get started with Actions

name: Build and test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Poetry
      - name: Install Poetry
        run: |
            (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -
            echo "$env:USERPROFILE\.poetry\bin" >> $GITHUB_PATH

      # Install all the projects development and runtime dependencies to a virtual environment
      - name: Poetry install
        run: poetry install
      
      # Generates the protobuf/grpc sources and creates the api packages
      - name: Poetry build
        run: poetry build
        
      - name: Run Python Unittest
        run: poetry run python -m unittest tests/all_tests.py
