name: Long tests

on:
  schedule:
    - cron: '0 3 * * *'

  workflow_dispatch:

permissions:
  contents: read

jobs:

  build_and_test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", 3.11, 3.12, 3.13, 3.14]
      fail-fast: false
    timeout-minutes: 90

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check if branch changed
        run: |
          echo "NEW_COMMITS=$(git log --since '1 day ago' --oneline | wc -l)" >> "$env:GITHUB_ENV"
      - name: Install dev environment
        #if: ${{ env.NEW_COMMITS > 0 }}
        uses: ./.github/workflows/install_dev_env
        with:
          python-version: ${{ matrix.python-version }}
          token: ${{ secrets.OAUTH_TOKEN }}
      - name: Run tests and upload test results
        #if: ${{ success() && env.NEW_COMMITS > 0 }}
        working-directory: ${{ github.workspace }}
        run: |
          poetry run pytest --junit-xml=TestResults/unittests.xml --cov-report=json:TestResults/coverage.json --cov --cov-branch -m "not authentication and not long"
      - name: Upload test results and coverage report to Quality Reporter
        uses: Volue/platform-workflow-library/quality-reporter@340eaf76e0e0afaa121727e56cb9935e162f061e # v1.0.3
        with:
          platform-tools-checkout-key: ${{ secrets.VOLUE_PLATFORM_TOOLS_READ_KEY }}
          grafana-publisher-token: ${{ secrets.VOLUE_PLATFORM_GRAFANA_METRICS_PUBLISHER_TOKEN }}
          required-test-count: "590"
          required-line-coverage: "80.0"
          required-branch-coverage: "70.0"
          required-method-coverage: "85.0"          
          programming-language: "python"
