name: Long tests

on:
  schedule:
    - cron: '0 3 * * *'

  workflow_dispatch:

jobs:

  build_and_test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", 3.11, 3.12, 3.13]
      fail-fast: false
    timeout-minutes: 90

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check if branch changed
        run: |
          echo "NEW_COMMITS=$(git log --since '1 day ago' --oneline | wc -l)" >> "$env:GITHUB_ENV"
      - name: Install dev environment
        if: ${{ env.NEW_COMMITS > 0 }}
        uses: ./.github/workflows/install_dev_env
        with:
          python-version: ${{ matrix.python-version }}
          token: ${{ secrets.OAUTH_TOKEN }}
      - name: Run long tests
        if: ${{ success() && env.NEW_COMMITS > 0 }}
        working-directory: ${{ github.workspace }}
        run: |
          poetry run pytest -m "long"
