name: GitHub pages

on:
  push:
    branches:
    - master

  workflow_dispatch:

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout origin/master to master/
      uses: actions/checkout@v2
      with:
        path: master

    - name: Checkout origin/gh-pages to gh-pages/
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

    - name: Build and publish page
      run: |
        git -C gh-pages config user.name $GITHUB_ACTOR
        git -C gh-pages config user.email "$GITHUB_ACTOR@bots.github.com"
        ./master/.github/workflows/pages.sh master/ gh-pages/
