name: GitHub pages

on:
  push:
    branches:
    - master

  workflow_dispatch:

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout origin/master to master/
      uses: actions/checkout@v2
      with:
        path: master

    - name: Checkout origin/gh-pages to gh-pages/
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Install Linux Kerberos dependency
      run: sudo apt-get install -y libkrb5-dev

    - name: Installing poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: '1.2.0'

    - name: Build and publish page
      run: |
        git -C gh-pages config user.name $GITHUB_ACTOR
        git -C gh-pages config user.email "$GITHUB_ACTOR@bots.github.com"
        ./master/.github/workflows/pages.sh master/ gh-pages/
