name: Usage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  checkout_and_use:
    runs-on: windows-2022
    strategy:
      matrix:
        python-version: [3.9, "3.10", 3.11, 3.12, 3.13]
      fail-fast: false
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v2
        with:
          path: repo
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout GitHub action
        uses: actions/checkout@v2
        with:
          repository: PowelAS/sme-run-mesh-service
          ref: master
          token: ${{ secrets.OAUTH_TOKEN }}
          path: .github/actions

      - name: Install and run Mesh server
        uses: ./.github/actions/
        id: download-mesh-server
        with:
          GITHUB_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          MESH_SERVICE_TAG: "v2.19.0.2447"

      # run one example before installing pytest packages and pandas
      # to check if all dependencies are installed together with Mesh Python SDK pip package
      - name: Install and test Python SDK (Windows)
        run: |
          python -m pip install git+https://github.com/Volue-Public/energy-mesh-python@${{ github.ref }}
          python ./repo/src/volue/mesh/examples/get_version.py
          if ($LASTEXITCODE) { exit $LASTEXITCODE }
          python -m pip install pytest pytest-asyncio==0.21.2 pandas
          python -m pytest ./repo/src/volue/mesh/tests -m "not authentication and not long"

      - name: Install Ubuntu 22.04 (WSL)
        uses: Vampire/setup-wsl@v5
        with:
          distribution: Ubuntu-22.04
          wsl-version: 2
          set-as-default: "true"
          update: "false"

      # run one example before installing pytest packages and pandas
      # to check if all dependencies are installed together with Mesh Python SDK pip package
      - name: Install and test Python SDK (Ubuntu 22.04)
        shell: wsl-bash {0}
        run: |
          sudo apt-get update
          sudo apt-get install --yes software-properties-common
          sudo add-apt-repository --yes ppa:deadsnakes/ppa
          sudo apt-get install --yes python${{ matrix.python-version }}

          if [[ "${{ matrix.python-version }}" == "3.9" ]]; then
            sudo apt-get install --yes python${{ matrix.python-version }}-distutils
          else
            :  # not needed for newer Python versions
          fi

          curl -sS https://bootstrap.pypa.io/get-pip.py | python${{ matrix.python-version }}
          sudo apt-get install --yes libkrb5-dev gcc
          sudo apt-get install --yes python${{ matrix.python-version }}-dev
          python${{ matrix.python-version }} -m pip install git+https://github.com/Volue-Public/energy-mesh-python@${{ github.ref }}
          python${{ matrix.python-version }} ./repo/src/volue/mesh/examples/get_version.py
          python${{ matrix.python-version }} -m pip install pytest pytest-asyncio==0.21.2 pandas
          python${{ matrix.python-version }} -m pytest ./repo/src/volue/mesh/tests -m "server and not long"
