name: Usage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  checkout_and_use:
    # Only windows-2019 hosts have wsl enabled
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]
      fail-fast: false
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2
        with:
          path: repo
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout GitHub action
        uses: actions/checkout@v2
        with:
          repository: PowelAS/sme-run-mesh-service
          ref: master
          token: ${{ secrets.OAUTH_TOKEN }}
          path: .github/actions

      - name: Install and run Mesh server
        uses: ./.github/actions/
        id: download-mesh-server
        with:
          GITHUB_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          MESH_SERVICE_TAG: 'v2.6.1.8'

      # run one example before installing pytest packages and pandas
      # to check if all dependencies are installed together with Mesh Python SDK pip package
      - name: Install and test Python SDK (Windows)
        run: |
          python -m pip install git+https://github.com/Volue-Public/energy-mesh-python@${{ github.ref }}
          python ./repo/src/volue/mesh/examples/get_version.py
          if ($LASTEXITCODE) { exit $LASTEXITCODE }
          python -m pip install pytest pytest-asyncio pandas
          python -m pytest --pyargs volue.mesh.tests -m "not authentication"

      - name: Install Ubuntu 20.04 (wsl1)
        uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          set-as-default: 'true'
          update: 'false'

      # run one example before installing pytest packages and pandas
      # to check if all dependencies are installed together with Mesh Python SDK pip package
      #
      # There is a problem with building the package volue.mesh using latest
      # pip (i.e. 23) on Python 3.10 on Linux. Downgrade to version 22.3.
      # As a workaround install either poetry via pip or downgrade to 22.3.
      - name: Install and test Python SDK (Ubuntu 20.04)
        shell: wsl-bash {0}
        run: |
          sudo apt-get update
          sudo apt-get install --yes software-properties-common
          sudo add-apt-repository --yes ppa:deadsnakes/ppa
          sudo apt-get install --yes python${{ matrix.python-version }}
          sudo apt-get install --yes python${{ matrix.python-version }}-distutils
          curl -sS https://bootstrap.pypa.io/get-pip.py | python${{ matrix.python-version }}
          sudo apt-get install --yes libkrb5-dev gcc
          sudo apt-get install --yes python${{ matrix.python-version }}-dev
          python${{ matrix.python-version }} -m pip install --upgrade pip==22.3
          python${{ matrix.python-version }} -m pip install git+https://github.com/Volue-Public/energy-mesh-python@${{ github.ref }}
          python${{ matrix.python-version }} ./repo/src/volue/mesh/examples/get_version.py
          python${{ matrix.python-version }} -m pip install pytest pytest-asyncio pandas
          python${{ matrix.python-version }} -m pytest --pyargs volue.mesh.tests -m "not authentication"
