name: Usage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  checkout_and_use:
    # Only windows-2019 hosts have wsl enabled
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Checkout GitHub action
        uses: actions/checkout@v2
        with:
          repository: PowelAS/sme-run-mesh-service
          ref: master
          token: ${{ secrets.OAUTH_TOKEN }}
          path: .github/actions

      - name: Install and run Mesh server
        uses: ./.github/actions/
        id: download-mesh-server
        with:
          GITHUB_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          MESH_SERVICE_TAG: 'meshservice_v2.2.0'

      - name: Install and test Python SDK (Windows)
        run: |
          python -m pip install git+https://${{ secrets.OAUTH_TOKEN }}@github.com/PowelAS/sme-mesh-python
          python -m pip install pytest pytest-asyncio
          python -m pytest --pyargs volue.mesh.tests -m "unittest or server"
      
      - name: Install Ubuntu 20.04 (wsl1)
        uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          set-as-default: 'true'
          update: 'false'
        
      - name: Install and test Python SDK (Ubuntu 20.04)
        shell: wsl-bash {0}
        run: |
          sudo apt-get update
          sudo apt-get install --yes software-properties-common
          sudo add-apt-repository --yes ppa:deadsnakes/ppa
          sudo apt-get install --yes python${{ matrix.python-version }}
          sudo apt-get install --yes python3-distutils
          sudo apt-get install --yes python3-pip
          python${{ matrix.python-version }} -m pip install git+https://${{ secrets.OAUTH_TOKEN }}@github.com/PowelAS/sme-mesh-python
          python${{ matrix.python-version }} -m pip install pytest pytest-asyncio
          python${{ matrix.python-version }} -m pytest --pyargs volue.mesh.tests -m "unittest or server"
          
