name: Usage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  checkout_and_use:
    # Only windows-2019 hosts have wsl enabled
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout GitHub action
        uses: actions/checkout@v2
        with:
          repository: PowelAS/sme-run-mesh-service
          ref: master
          token: ${{ secrets.OAUTH_TOKEN }}
          path: .github/actions

      - name: Install and run Mesh server
        uses: ./.github/actions/
        id: download-mesh-server
        with:
          GITHUB_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          MESH_SERVICE_TAG: 'v2.3.0.12'

      # because the ref name (either branch name or pull request number)
      # will be used in different steps (using different shells)
      # create a separate step for just getting the ref name
      - name: Get ref name
        shell: bash
        run: echo "::set-output name=ref_name::$(echo ${GITHUB_REF})"
        id: get_ref_name

      # run one example before installing pytest packages and pandas
      # to check if all dependencies are installed together with Mesh Python SDK pip package
      - name: Install and test Python SDK (Windows)
        run: |
          python -m pip install git+https://${{ secrets.OAUTH_TOKEN }}@github.com/PowelAS/sme-mesh-python@${{ steps.get_ref_name.outputs.ref_name }}
          curl https://${{ secrets.OAUTH_TOKEN }}@github.com/PowelAS/sme-mesh-python/${{ github.ref_name }}/src/volue/mesh/examples/get_version.py -o get_version.py
          python ./get_version.py
          python -m pip install pytest pytest-asyncio pandas
          python -m pytest --pyargs volue.mesh.tests -m "not authentication"

      - name: Install Ubuntu 20.04 (wsl1)
        uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          set-as-default: 'true'
          update: 'false'

      # run one example before installing pytest packages and pandas
      # to check if all dependencies are installed together with Mesh Python SDK pip package
      - name: Install and test Python SDK (Ubuntu 20.04)
        shell: wsl-bash {0}
        run: |
          sudo apt-get update
          sudo apt-get install --yes software-properties-common
          sudo add-apt-repository --yes ppa:deadsnakes/ppa
          sudo apt-get install --yes python${{ matrix.python-version }}
          sudo apt-get install --yes python3-distutils
          sudo apt-get install --yes python3-pip
          sudo apt-get install --yes libkrb5-dev
          sudo apt-get install --yes python${{ matrix.python-version }}-dev
          python${{ matrix.python-version }} -m pip install git+https://${{ secrets.OAUTH_TOKEN }}@github.com/PowelAS/sme-mesh-python@${{ steps.get_ref_name.outputs.ref_name }}
          curl https://${{ secrets.OAUTH_TOKEN }}@github.com/PowelAS/sme-mesh-python/${{ github.ref_name }}/src/volue/mesh/examples/get_version.py -o get_version.py
          python ./get_version.py
          python${{ matrix.python-version }} -m pip install pytest pytest-asyncio pandas
          python${{ matrix.python-version }} -m pytest --pyargs volue.mesh.tests -m "not authentication"
